# Generated by Django 4.2 on 2024-07-19 18:12

import client_ticket.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ticket_images/', validators=[client_ticket.models.validate_image])),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ticket_images/', validators=[client_ticket.models.validate_image])),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ticket_images/', validators=[client_ticket.models.validate_image])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=8)),
                ('is_visited', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_time', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
    ]
