# Generated by Django 4.2 on 2024-07-08 10:02

import client_ticket.models
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ticket_images/",
                        validators=[client_ticket.models.validate_image],
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ticket_images/",
                        validators=[client_ticket.models.validate_image],
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ticket_images/",
                        validators=[client_ticket.models.validate_image],
                    ),
                ),
                (
                    "created_time",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("answered", "Answered")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "answered_time",
                    django_jalali.db.models.jDateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "ticket",
            },
        ),
    ]
