# Generated by Django 4.2 on 2024-07-08 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialSourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[("Card", "Card"), ("Cash", "Cash")], max_length=4
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Card number must be exactly 16 digits.",
                                regex="^\\d{16}$",
                            )
                        ],
                    ),
                ),
                ("is_calculate", models.BooleanField(default=True)),
                ("is_enable", models.BooleanField(default=True)),
                ("remain", models.IntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_sources",
                        to="client_account.accountmodel",
                        verbose_name="account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Source",
                "verbose_name_plural": "Financial Sources",
                "db_table": "financial source",
            },
        ),
    ]
