# Generated by Django 4.2 on 2024-07-10 13:58

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("client_source", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsourcemodel",
            name="card_number",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره کارت بایستی 16 رقم باشد.", regex="^\\d{16}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="financialsourcemodel",
            name="created_time",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="financialsourcemodel",
            name="updated_time",
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
