# Generated by Django 4.2 on 2024-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsourcemodel',
            name='icon_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='financialsourcemodel',
            name='icon_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialsourcemodel',
            name='remain',
            field=models.IntegerField(default=0),
        ),
    ]
