# Generated by Django 4.2 on 2024-08-04 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقم و به فرمت 09xxxxxxxxx باشد.', regex='^09\\d{9}$')])),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='client_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='client_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید 11 رقم و به فرمت 09xxxxxxxxx باشد.', regex='^09\\d{9}$')])),
                ('otp', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='کد عددی صحت شماره تلفن باید 6 رقم باشد.', regex='^\\d{6}$')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Totp',
                'verbose_name_plural': "Totp's",
                'db_table': 'totp',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('session_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_unit', models.CharField(choices=[('Rial', 'Rial'), ('Toman', 'Toman')], default='Toman', max_length=5)),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
