# Generated by Django 4.2 on 2024-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmodel',
            options={'verbose_name': 'User session', 'verbose_name_plural': 'User sessions'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
