# Generated by Django 4.2 on 2024-07-13 11:51

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Expense", "Expense"),
                            ("Transfer", "Transfer"),
                        ],
                        max_length=8,
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                (
                    "created_time",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_time", django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Default Category",
                "verbose_name_plural": "Default Categories",
                "db_table": "default_category",
                "unique_together": {("name", "transaction_type", "is_default")},
            },
        ),
    ]
