# Generated by Django 4.2 on 2024-08-04 18:12

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon_name', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=7)),
                ('icon_fg_color', models.CharField(max_length=6)),
                ('icon_bg_color', models.CharField(max_length=6)),
                ('is_default', models.BooleanField(default=False)),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Category',
                'verbose_name_plural': 'Default Categories',
                'db_table': 'default_categories',
                'unique_together': {('name', 'transaction_type', 'is_default')},
            },
        ),
    ]
