# Generated by Django 4.2 on 2024-07-08 10:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("credit", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_time",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_time", django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
            },
        ),
    ]
