# Generated by Django 4.2 on 2024-08-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_auth', '0001_initial'),
        ('client_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='client_auth.profilemodel', verbose_name='profile'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmodel',
            unique_together={('profile', 'name')},
        ),
    ]
