# Generated by Django 4.2 on 2024-07-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_user", "0002_alter_totpmodel_phone_number_and_more"),
        ("client_account", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountmodel", unique_together={("profile", "name")},
        ),
    ]
