# Generated by Django 4.2 on 2024-09-03 14:42

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('client_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
