# Generated by Django 4.2 on 2024-08-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_auth', '0001_initial'),
        ('admin_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='client_auth.profilemodel', verbose_name='profile'),
        ),
    ]
