# Generated by Django 4.2 on 2024-07-10 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpmodel",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تلفن باید 11 رقم و به فرمت 09xxxxxxxxx باشد.",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تلفن باید 11 رقم و به فرمت 09xxxxxxxxx باشد.",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
    ]
