# Generated by Django 4.2 on 2024-07-19 18:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_account', '0001_initial'),
        ('client_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages='نام انتخابی نهایت 30 کاراکتر است.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, error_messages='سقف بودجه بندی 16 رقم است.', max_digits=16)),
                ('cycle_start_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 21))),
                ('cycle_end_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 7, 21))),
                ('remaining', models.DecimalField(decimal_places=0, error_messages='سقف بودجه بندی 16 رقم است.', max_digits=16)),
                ('alarm_percent', models.PositiveIntegerField(error_messages='درصد هشدار برای باقی مانده بودجه بندی بین 1 الی 99 درصد است.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Alarm Percent')),
                ('is_closed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='client_account.accountmodel', verbose_name='account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='client_category.categorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budget',
                'unique_together': {('account', 'name', 'category', 'cycle_start_date')},
            },
        ),
    ]
