# Generated by Django 4.2 on 2024-07-08 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_account", "0001_initial"),
        ("client_category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=16)),
                ("cycle_start_date", django_jalali.db.models.jDateField()),
                ("cycle_end_date", django_jalali.db.models.jDateField()),
                (
                    "remaining",
                    models.DecimalField(decimal_places=0, default=0, max_digits=16),
                ),
                (
                    "alarm_percent",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Alarm Percent",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="client_account.accountmodel",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="client_category.categorymodel",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budget",
            },
        ),
    ]
