# Generated by Django 4.2 on 2024-09-02 18:09

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('client_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='cycle_end_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 21)),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='cycle_start_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 8, 22)),
        ),
    ]
