# Generated by Django 4.2 on 2024-08-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('type_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_format', models.CharField(blank=True, max_length=255)),
                ('amount_after_char', models.IntegerField(default=-1)),
                ('amount_before_char', models.IntegerField(default=-1)),
                ('amount_regex', models.CharField(max_length=255)),
                ('account_number_format', models.CharField(blank=True, max_length=255)),
                ('account_number_after_char', models.IntegerField(default=-1)),
                ('account_number_before_char', models.IntegerField(default=-1)),
                ('account_number_regex', models.CharField(max_length=255)),
                ('date_format', models.CharField(blank=True, max_length=255)),
                ('date_after_char', models.IntegerField(default=-1)),
                ('date_before_char', models.IntegerField(default=-1)),
                ('date_regex', models.CharField(max_length=255)),
                ('time_format', models.CharField(blank=True, max_length=255)),
                ('time_after_char', models.IntegerField(default=-1)),
                ('time_before_char', models.IntegerField(default=-1)),
                ('time_regex', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='admin_bank.bankmodel')),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'db_table': 'transaction_types',
            },
        ),
    ]
