# Generated by Django 4.2 on 2024-08-04 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='adminusermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='admin_user_permissions', to='auth.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='adminusermodel',
            unique_together={('user', 'username')},
        ),
    ]
